spring.application.name=service-ops-api

spring.datasource.url=${SERVICE_OPS_DB_URL:jdbc:postgresql://localhost:5432/service_ops_api}
spring.datasource.username=${SERVICE_OPS_DB_USERNAME:service_ops}
spring.datasource.password=${SERVICE_OPS_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
