package com.thundercrew.opsapi.common.api;

public enum ErrorCode {
    VALIDATION_FAILED,
    REFERENCE_NOT_FOUND,
    REFERENCE_DELETED,
    DUPLICATE_ACTIVE_RELATION,
    PERIOD_OVERLAP,
    INVALID_STATE_TRANSITION,
    STALE_TELEMETRY_IGNORED,
    IDEMPOTENT_REPLAY,
    INTERNAL_ERROR
}
